version: '3'

services:
  collectd:
    build: 
      context: .
      dockerfile: Dockerfile-collectd
    container_name: collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd.conf
    tty: true
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./collectd.sh:/docker-entrypoint-initdb.d/collectd.sh
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
