version: '3'

services:

  filebeat:
    build:
      context: ./stuff
    container_name: filebeat
    hostname: filebeat
    ports:
      - "80:80"
    volumes:
      - /var/log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.6.1
    container_name: logstash
    hostname: logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    volumes:
      - ./stuff/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"